# Generated by Django 5.2.10 on 2026-01-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_kk', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_kk', models.TextField(blank=True, null=True)),
                ('date_display', models.CharField(help_text="Text representation of date, e.g. '20-25 Jan'", max_length=100)),
                ('date_display_ru', models.CharField(help_text="Text representation of date, e.g. '20-25 Jan'", max_length=100, null=True)),
                ('date_display_kk', models.CharField(help_text="Text representation of date, e.g. '20-25 Jan'", max_length=100, null=True)),
                ('sort_date', models.DateField(blank=True, help_text='For sorting purposes', null=True)),
                ('event_type', models.CharField(blank=True, help_text='INTERVIEW/DEADLINE/OPENDAY', max_length=50)),
            ],
            options={
                'ordering': ['sort_date'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('question_ru', models.CharField(max_length=255, null=True)),
                ('question_kk', models.CharField(max_length=255, null=True)),
                ('answer', models.TextField()),
                ('answer_ru', models.TextField(null=True)),
                ('answer_kk', models.TextField(null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GrantBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('text_ru', models.CharField(max_length=255, null=True)),
                ('text_kk', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('program', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_kk', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_kk', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master')], default='BACHELOR', max_length=20)),
                ('tags', models.CharField(blank=True, help_text="e.g. 'UNT: Math+Physics'", max_length=255)),
                ('tags_ru', models.CharField(blank=True, help_text="e.g. 'UNT: Math+Physics'", max_length=255, null=True)),
                ('tags_kk', models.CharField(blank=True, help_text="e.g. 'UNT: Math+Physics'", max_length=255, null=True)),
                ('brochure', models.FileField(blank=True, null=True, upload_to='brochures/')),
                ('brochure_ru', models.FileField(blank=True, null=True, upload_to='brochures/')),
                ('brochure_kk', models.FileField(blank=True, null=True, upload_to='brochures/')),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+7 (777) 777-77-77', max_length=50)),
                ('email', models.EmailField(default='info@shakarim.edu.kz', max_length=254)),
                ('address', models.CharField(default='Semey, ...', max_length=255)),
                ('address_ru', models.CharField(default='Semey, ...', max_length=255, null=True)),
                ('address_kk', models.CharField(default='Semey, ...', max_length=255, null=True)),
                ('whatsapp_link', models.URLField(blank=True)),
                ('telegram_link', models.URLField(blank=True)),
                ('career_test_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='TuitionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(help_text='Bachelor/Master', max_length=100)),
                ('level_ru', models.CharField(help_text='Bachelor/Master', max_length=100, null=True)),
                ('level_kk', models.CharField(help_text='Bachelor/Master', max_length=100, null=True)),
                ('study_format', models.CharField(help_text='Full-time/Part-time', max_length=100)),
                ('study_format_ru', models.CharField(help_text='Full-time/Part-time', max_length=100, null=True)),
                ('study_format_kk', models.CharField(help_text='Full-time/Part-time', max_length=100, null=True)),
                ('price', models.CharField(help_text='Price per year', max_length=100)),
                ('price_ru', models.CharField(help_text='Price per year', max_length=100, null=True)),
                ('price_kk', models.CharField(help_text='Price per year', max_length=100, null=True)),
            ],
        ),
    ]
