# Generated by Django 5.2.10 on 2026-01-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='advantage_1',
            field=models.TextField(blank=True, verbose_name='Артықшылығы 1 / Преимущество 1'),
        ),
        migrations.AddField(
            model_name='program',
            name='advantage_1_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Артықшылығы 1 / Преимущество 1'),
        ),
        migrations.AddField(
            model_name='program',
            name='advantage_1_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Артықшылығы 1 / Преимущество 1'),
        ),
        migrations.AddField(
            model_name='program',
            name='advantage_2',
            field=models.TextField(blank=True, verbose_name='Артықшылығы 2 / Преимущество 2'),
        ),
        migrations.AddField(
            model_name='program',
            name='advantage_2_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Артықшылығы 2 / Преимущество 2'),
        ),
        migrations.AddField(
            model_name='program',
            name='advantage_2_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Артықшылығы 2 / Преимущество 2'),
        ),
        migrations.AddField(
            model_name='program',
            name='advantage_3',
            field=models.TextField(blank=True, verbose_name='Артықшылығы 3 / Преимущество 3'),
        ),
        migrations.AddField(
            model_name='program',
            name='advantage_3_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Артықшылығы 3 / Преимущество 3'),
        ),
        migrations.AddField(
            model_name='program',
            name='advantage_3_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Артықшылығы 3 / Преимущество 3'),
        ),
        migrations.AddField(
            model_name='program',
            name='career_track',
            field=models.TextField(blank=True, verbose_name='Мансап жолы / Карьерный трек'),
        ),
        migrations.AddField(
            model_name='program',
            name='career_track_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Мансап жолы / Карьерный трек'),
        ),
        migrations.AddField(
            model_name='program',
            name='career_track_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Мансап жолы / Карьерный трек'),
        ),
        migrations.AddField(
            model_name='program',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код ОП'),
        ),
        migrations.AddField(
            model_name='program',
            name='hard_skills',
            field=models.TextField(blank=True, verbose_name='Hard Skills'),
        ),
        migrations.AddField(
            model_name='program',
            name='hard_skills_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Hard Skills'),
        ),
        migrations.AddField(
            model_name='program',
            name='hard_skills_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Hard Skills'),
        ),
        migrations.AddField(
            model_name='program',
            name='interesting_subjects',
            field=models.TextField(blank=True, help_text='Список', verbose_name='Қызықты пәндер / Интересные дисциплины'),
        ),
        migrations.AddField(
            model_name='program',
            name='interesting_subjects_kk',
            field=models.TextField(blank=True, help_text='Список', null=True, verbose_name='Қызықты пәндер / Интересные дисциплины'),
        ),
        migrations.AddField(
            model_name='program',
            name='interesting_subjects_ru',
            field=models.TextField(blank=True, help_text='Список', null=True, verbose_name='Қызықты пәндер / Интересные дисциплины'),
        ),
        migrations.AddField(
            model_name='program',
            name='lang_eng',
            field=models.BooleanField(default=False, verbose_name='Оқыту тілі: English'),
        ),
        migrations.AddField(
            model_name='program',
            name='lang_kaz',
            field=models.BooleanField(default=False, verbose_name='Оқыту тілі: Қазақ'),
        ),
        migrations.AddField(
            model_name='program',
            name='lang_rus',
            field=models.BooleanField(default=False, verbose_name='Оқыту тілі: Русский'),
        ),
        migrations.AddField(
            model_name='program',
            name='main_info',
            field=models.TextField(blank=True, verbose_name='Негізгі ақпарат / Основная информация'),
        ),
        migrations.AddField(
            model_name='program',
            name='main_info_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Негізгі ақпарат / Основная информация'),
        ),
        migrations.AddField(
            model_name='program',
            name='main_info_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Негізгі ақпарат / Основная информация'),
        ),
        migrations.AddField(
            model_name='program',
            name='media_links',
            field=models.TextField(blank=True, help_text='Гиперссылки на инстаграмм', verbose_name='Медиа-контент (Instagram Links)'),
        ),
        migrations.AddField(
            model_name='program',
            name='partners',
            field=models.TextField(blank=True, help_text='Список', verbose_name='Практика өтетін ұйымдар / Компании партнеры'),
        ),
        migrations.AddField(
            model_name='program',
            name='partners_kk',
            field=models.TextField(blank=True, help_text='Список', null=True, verbose_name='Практика өтетін ұйымдар / Компании партнеры'),
        ),
        migrations.AddField(
            model_name='program',
            name='partners_ru',
            field=models.TextField(blank=True, help_text='Список', null=True, verbose_name='Практика өтетін ұйымдар / Компании партнеры'),
        ),
        migrations.AddField(
            model_name='program',
            name='photo_video_links',
            field=models.TextField(blank=True, help_text='Гиперссылки на инстаграмм', verbose_name='Фото/видео сілтеме'),
        ),
        migrations.AddField(
            model_name='program',
            name='profession_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Лауазым 1 / Профессия 1'),
        ),
        migrations.AddField(
            model_name='program',
            name='profession_1_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лауазым 1 / Профессия 1'),
        ),
        migrations.AddField(
            model_name='program',
            name='profession_1_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лауазым 1 / Профессия 1'),
        ),
        migrations.AddField(
            model_name='program',
            name='profession_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Лауазым 2 / Профессия 2'),
        ),
        migrations.AddField(
            model_name='program',
            name='profession_2_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лауазым 2 / Профессия 2'),
        ),
        migrations.AddField(
            model_name='program',
            name='profession_2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лауазым 2 / Профессия 2'),
        ),
        migrations.AddField(
            model_name='program',
            name='profession_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Лауазым 3 / Профессия 3'),
        ),
        migrations.AddField(
            model_name='program',
            name='profession_3_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лауазым 3 / Профессия 3'),
        ),
        migrations.AddField(
            model_name='program',
            name='profession_3_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лауазым 3 / Профессия 3'),
        ),
        migrations.AddField(
            model_name='program',
            name='profession_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Лауазым 4 / Профессия 4'),
        ),
        migrations.AddField(
            model_name='program',
            name='profession_4_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лауазым 4 / Профессия 4'),
        ),
        migrations.AddField(
            model_name='program',
            name='profession_4_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лауазым 4 / Профессия 4'),
        ),
        migrations.AddField(
            model_name='program',
            name='profession_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Лауазым 5 / Профессия 5'),
        ),
        migrations.AddField(
            model_name='program',
            name='profession_5_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лауазым 5 / Профессия 5'),
        ),
        migrations.AddField(
            model_name='program',
            name='profession_5_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лауазым 5 / Профессия 5'),
        ),
        migrations.AddField(
            model_name='program',
            name='salary_start',
            field=models.CharField(blank=True, max_length=255, verbose_name='Орташа бастапқы жалақы / Средняя зарплата на старте'),
        ),
        migrations.AddField(
            model_name='program',
            name='salary_start_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Орташа бастапқы жалақы / Средняя зарплата на старте'),
        ),
        migrations.AddField(
            model_name='program',
            name='salary_start_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Орташа бастапқы жалақы / Средняя зарплата на старте'),
        ),
        migrations.AddField(
            model_name='program',
            name='slogan',
            field=models.CharField(blank=True, max_length=500, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='program',
            name='slogan_kk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='program',
            name='slogan_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='program',
            name='social_proof',
            field=models.TextField(blank=True, verbose_name='Әлеуметтік дәлел / Социальное доказательство'),
        ),
        migrations.AddField(
            model_name='program',
            name='social_proof_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Әлеуметтік дәлел / Социальное доказательство'),
        ),
        migrations.AddField(
            model_name='program',
            name='social_proof_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Әлеуметтік дәлел / Социальное доказательство'),
        ),
        migrations.AddField(
            model_name='program',
            name='soft_skills',
            field=models.TextField(blank=True, verbose_name='Soft Skills'),
        ),
        migrations.AddField(
            model_name='program',
            name='soft_skills_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Soft Skills'),
        ),
        migrations.AddField(
            model_name='program',
            name='soft_skills_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Soft Skills'),
        ),
        migrations.AddField(
            model_name='program',
            name='star_graduates',
            field=models.TextField(blank=True, help_text='Список', verbose_name='Табысты түлектер / Звездные выпускники'),
        ),
        migrations.AddField(
            model_name='program',
            name='star_graduates_kk',
            field=models.TextField(blank=True, help_text='Список', null=True, verbose_name='Табысты түлектер / Звездные выпускники'),
        ),
        migrations.AddField(
            model_name='program',
            name='star_graduates_ru',
            field=models.TextField(blank=True, help_text='Список', null=True, verbose_name='Табысты түлектер / Звездные выпускники'),
        ),
        migrations.AddField(
            model_name='program',
            name='star_teachers',
            field=models.TextField(blank=True, help_text='Список', verbose_name='Белгілі оқытушылар / Звездные преподаватели'),
        ),
        migrations.AddField(
            model_name='program',
            name='star_teachers_kk',
            field=models.TextField(blank=True, help_text='Список', null=True, verbose_name='Белгілі оқытушылар / Звездные преподаватели'),
        ),
        migrations.AddField(
            model_name='program',
            name='star_teachers_ru',
            field=models.TextField(blank=True, help_text='Список', null=True, verbose_name='Белгілі оқытушылар / Звездные преподаватели'),
        ),
        migrations.AddField(
            model_name='program',
            name='target_audience',
            field=models.TextField(blank=True, verbose_name='Бұл бағдарлама кімге арналған? / Для кого эта программа?'),
        ),
        migrations.AddField(
            model_name='program',
            name='target_audience_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Бұл бағдарлама кімге арналған? / Для кого эта программа?'),
        ),
        migrations.AddField(
            model_name='program',
            name='target_audience_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Бұл бағдарлама кімге арналған? / Для кого эта программа?'),
        ),
        migrations.AddField(
            model_name='program',
            name='unt_subjects',
            field=models.CharField(blank=True, max_length=255, verbose_name='ҰБТ бейіндік пәндері / Профильные предметы ЕНТ'),
        ),
        migrations.AddField(
            model_name='program',
            name='unt_subjects_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ҰБТ бейіндік пәндері / Профильные предметы ЕНТ'),
        ),
        migrations.AddField(
            model_name='program',
            name='unt_subjects_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ҰБТ бейіндік пәндері / Профильные предметы ЕНТ'),
        ),
        migrations.AddField(
            model_name='program',
            name='usp',
            field=models.TextField(blank=True, verbose_name='Уникалды сауда ұсынысы / УТП'),
        ),
        migrations.AddField(
            model_name='program',
            name='usp_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Уникалды сауда ұсынысы / УТП'),
        ),
        migrations.AddField(
            model_name='program',
            name='usp_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Уникалды сауда ұсынысы / УТП'),
        ),
        migrations.AddField(
            model_name='program',
            name='what_will_learn',
            field=models.TextField(blank=True, verbose_name='Не үйретеміз? / Чему научим?'),
        ),
        migrations.AddField(
            model_name='program',
            name='what_will_learn_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Не үйретеміз? / Чему научим?'),
        ),
        migrations.AddField(
            model_name='program',
            name='what_will_learn_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Не үйретеміз? / Чему научим?'),
        ),
    ]
