# Generated by Django 5.2.10 on 2026-02-03 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_program_advantage_1_program_advantage_1_kk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UNTSubjectComb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Предметы сдачи (напр. Математика - Физика)')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='unt_combination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='core.untsubjectcomb', verbose_name='Комбинация ЕНТ'),
        ),
    ]
