# Generated by Django 5.2.10 on 2026-02-03 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_untsubjectcomb_program_unt_combination'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A', 'A - IT'), ('B', 'B - STEM'), ('C', 'C - Business'), ('D', 'D - Pedagogy'), ('E', 'E - Agro/Bio'), ('F', 'F - Humanities')], max_length=2, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_kk', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_kk', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='career_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='core.careerprofile', verbose_name='Профориентационный профиль'),
        ),
    ]
