# Generated by Django 5.2.10 on 2026-02-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_careerprofile_program_career_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='passing_score',
            field=models.CharField(blank=True, max_length=50, verbose_name='Проходной балл'),
        ),
    ]
