# Generated by Django 5.2.10 on 2026-02-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_program_passing_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantbenefit',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='grantbenefit',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='grantbenefit',
            name='text_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='grantbenefit',
            name='text_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
