# Generated by Django 5.2.10 on 2026-01-30 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_program_advantage_1_program_advantage_1_kk_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(max_length=12, unique=True, verbose_name='ИИН / ЖСН')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения / Туған күні')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, verbose_name='Пол / Жынысы')),
                ('address', models.TextField(blank=True, verbose_name='Адрес проживания / Тұрғылықты мекенжайы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль абитуриента',
                'verbose_name_plural': 'Профили абитуриентов',
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_language', models.CharField(choices=[('KZ', 'Қазақша'), ('RU', 'Русский'), ('EN', 'English')], default='KZ', max_length=10, verbose_name='Язык обучения / Оқу тілі')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик / Қаралама'), ('SUBMITTED', 'Отправлено / Жіберілді'), ('UNDER_REVIEW', 'На рассмотрении / Қаралуда'), ('APPROVED', 'Одобрено / Мақұлданды'), ('REJECTED', 'Отклонено / Қабылданбады')], default='DRAFT', max_length=20, verbose_name='Статус')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.program', verbose_name='Выбранная программа / Таңдалған бағдарлама')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applicants.applicantprofile')),
            ],
            options={
                'verbose_name': 'Заявка на поступление',
                'verbose_name_plural': 'Заявки на поступление',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('ID_FRONT', 'Уд. личности (лиц.) / Жеке куәлік (алдыңғы)'), ('ID_BACK', 'Уд. личности (об.) / Жеке куәлік (артқы)'), ('CERTIFICATE', 'Аттестат/Диплом'), ('PHOTO', 'Фото 3x4'), ('MED_075', 'Медицинская справка 075 / 075 медициналық анықтама'), ('UNT_CERT', 'Сертификат ЕНТ / ҰБТ сертификаты'), ('OTHER', 'Другое / Басқа')], max_length=20, verbose_name='Тип документа / Құжат түрі')),
                ('file', models.FileField(upload_to='applicant_docs/%Y/%m/%d/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверено / Тексерілді')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applicants.applicantprofile')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='DormitoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_dorm', models.BooleanField(default=True, verbose_name='Нуждается в общежитии / Жатақхана қажет')),
                ('priority_category', models.CharField(blank=True, max_length=100, verbose_name='Льготная категория / Жеңілдік санаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorm_requests', to='applicants.applicantprofile')),
            ],
            options={
                'verbose_name': 'Заявка на общежитие',
                'verbose_name_plural': 'Заявки на общежитие',
            },
        ),
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255, verbose_name='Название учебного заведения / Оқу орнының атауы')),
                ('graduation_year', models.IntegerField(verbose_name='Год окончания / Бітірген жылы')),
                ('certificate_number', models.CharField(blank=True, max_length=50, verbose_name='Номер аттестата/диплома / Аттестат/диплом нөмірі')),
                ('average_score', models.FloatField(blank=True, null=True, verbose_name='Средний балл / Орташа балл')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='applicants.applicantprofile')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
    ]
