# Generated by Django 5.2.10 on 2026-01-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество / Әкесінің аты'),
        ),
    ]
