# Generated by Django 5.2.10 on 2026-02-03 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_applicantprofile_patronymic'),
        ('core', '0004_careerprofile_program_career_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='manager_comment',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='study_language',
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='language',
            field=models.CharField(choices=[('KZ', 'Қазақша'), ('RU', 'Русский'), ('EN', 'English')], default='KZ', max_length=2, verbose_name='Язык обучения / Оқу тілі'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('ID_FRONT', 'Удостоверение личности (лиц.)'), ('ID_BACK', 'Удостоверение личности (обр.)'), ('CERTIFICATE', 'Аттестат/Диплом'), ('PHOTO', 'Фото 3x4'), ('MED_075', 'Справка 075у'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.program', verbose_name='Образовательная программа / Білім беру бағдарламасы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='applicant_docs/%Y/%m/', verbose_name='Файл'),
        ),
        migrations.CreateModel(
            name='CareerTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(default=dict, verbose_name='Баллы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
            },
        ),
        migrations.DeleteModel(
            name='DormitoryRequest',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
