# Generated by Django 5.2.10 on 2026-02-03 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_remove_notification_user_and_more'),
        ('core', '0004_careerprofile_program_career_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='careertestresult',
            name='top_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.careerprofile', verbose_name='Результат (Профиль)'),
        ),
    ]
